version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  react:
    build:
      context: frontendold
      dockerfile: ../docker/react/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontendold:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translation_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db-data:
